# Node Configuration for debuging
# Created: 2026-03-13T06:53:14.893Z
# ========================================

# Reverse Logic Relay
# Jika true: relay.json "on" -> kirim "off" ke ESP, dan sebaliknya
# Default: false
reverse-logic-relay = true
