# Schedule Configuration for device
# Created: 2026-03-13T10:57:16.974Z
# ========================================

use-relay-feedback = false
# Jika false maka gunakan feedback dari sensor, jika true gunakan feedback dari relay itself
# Menentukan sumber feedback yang digunakan oleh sistem schedule untuk memverifikasi status perangkat.
# false → Sistem membaca feedback dari sensor atau status asli perangkat.
# true → Sistem membaca feedback dari status relay itu sendiri.

feedback-timeout-ms = 5000
# Jika feedback tidak berubah meskipun state baru udah dikirim, maka anggap feedback timeout
# dan change state lagi. sampai feedback beneran berubah sesuai state yang dikirim.

realtime-state-enforcement = true
# Menentukan apakah sistem akan langsung mengoreksi perubahan status yang terjadi di luar kendali schedule.

# ========================================
# Jangan hapus komentar di atas!
# File ini digunakan oleh schedule system
